[project]
name = "neural-networks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "optuna>=4.2.1",
    "plotly>=6.0.1",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
]
