version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: farm_db
    restart: always
    environment:
      POSTGRES_USER: dm
      POSTGRES_PASSWORD: dm123
      POSTGRES_DB: farm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: